spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 1000
        # dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  token:
    header: X-SEPARTNERS-AUTH
    issuer: separtners
    client-secret: Rel3Bjce2MajBo09qgkNgYaTuzvJe8iwnBFhsDS5
    expiry-seconds: 300

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

app:
  company-name: Separtners